### ISSUE TITLE
undefined method `inject_defaults!' for RuboCop::ConfigLoader:Class with rubocop < 1.50

### ISSUE THREAD

**Issue by agrieser-healthie** [rubocop/rubocop-factory_bot#89]
Per gemspec, requires rubocop `~> 1.33`, but with versions below `1.50` it produces an exception:

```
undefined method `inject_defaults!' for RuboCop::ConfigLoader:Class
```

Upgrading rubocop to `1.50` or higher fixes this issue

ruby 3.2.2
Rails 6.1.7.6
factory_bot (6.4.2)
factory_bot_rails (6.4.2)

**Comment by pirj** [comment]
I thought [it](https://github.com/rubocop/rubocop/pull/11265/commits/66bb7a222533d9fb20661d54acf29b04a415c84d) was released earlier than in 1.50, but certainly not in 1.33.
Our parent [depends on 1.40](https://github.com/rubocop/rubocop-rspec/blob/16bd30f3d7fb7eb8b7546a1be4e38e3c716d5119/rubocop-rspec.gemspec#L40), should we follow?

Do you use this gem without rubocop-rspec, @agrieser-healthie ?

**Comment by pirj** [comment]
This gem is a dependency of rubocop-rspec since [2.22](https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2220-2023-05-06), and all cops were part of it prior to that. But in 3.0 we plan to separate them. Thanks for being an early adopter.

As for rubocop-rspec and inject_defaults I recall I [couldn’t make it work](https://github.com/rubocop/rubocop-rspec/pull/1522).

Would you please send a PR to bump the dependency to 1.41 or whatever version of rubocop contains this, @agrieser-healthie ?

**Comment by pirj** [comment]
@agrieser-healthie can you please check if using rubocop-factory_bot from a bump-rubocop-version branch fixes your issue?

**Comment by pirj** [comment]
Or `master` since we’ve merged the fix
